"""Data access. PostgresRepository is used when DATABASE_URL is set;
MemoryRepository keeps local development working without a database."""

from typing import Any, Protocol

from .. import settings
from ..models import Chain, CoffeeShop, NewShop, Report, ShopClaim, ShopPhoto, User


class Repository(Protocol):
    def list_shops(self, filter: dict, user_id: str | None = None) -> tuple[list[CoffeeShop], int]: ...
    def get_shop(self, shop_id: str, user_id: str | None = None) -> CoffeeShop | None: ...
    def list_cities(self) -> list[str]: ...
    def list_reports(self, shop_id: str, limit: int | None = None) -> list[Report]: ...
    def count_reports(self, shop_id: str) -> int: ...
    def add_report(self, report: dict) -> Report: ...
    def find_matching_shop(self, name: str, lat: float, lng: float) -> CoffeeShop | None: ...
    def upsert_shops(self, shops: list[NewShop]) -> list[CoffeeShop]: ...
    def enrich_shop(self, shop_id: str, patch: dict) -> None: ...
    def set_shop_meta(self, shop_id: str, meta: dict) -> None: ...
    def upsert_user(self, user: dict) -> User: ...
    def get_user(self, user_id: str) -> User | None: ...
    def list_owned_shops(self, user_id: str) -> list[CoffeeShop]: ...
    def create_claim(self, user_id: str, shop_id: str, note: str | None) -> ShopClaim: ...
    def list_claims(self, user_id: str | None = None, status: str | None = None) -> list[ShopClaim]: ...
    def resolve_claim(self, claim_id: str, approve: bool) -> ShopClaim | None: ...
    def set_shop_status(self, user_id: str, shop_id: str, saved: bool | None, been: bool | None) -> None: ...
    def user_stats(self, user_id: str) -> dict[str, Any]: ...
    def list_photos(self, shop_id: str, limit: int | None = None) -> list[ShopPhoto]: ...
    def count_photos(self, shop_id: str) -> int: ...
    def add_photos(self, shop_id: str, user_id: str | None, photos: list[dict]) -> list[ShopPhoto]: ...
    def get_chain(self, chain_id: str) -> Chain | None: ...
    def list_chain_shops(self, chain_id: str, user_id: str | None = None) -> list[CoffeeShop]: ...
    def relink_chains(self) -> int: ...


def create_repository() -> Repository:
    if settings.DATABASE_URL:
        from .postgres import PostgresRepository

        print("repository: Postgres (DATABASE_URL set)")
        return PostgresRepository(settings.DATABASE_URL)
    from .memory import MemoryRepository

    print("repository: in-memory, non-persistent (set DATABASE_URL to use Neon)")
    return MemoryRepository()
