"""switch primary keys from uuid to bigint

New ids count up from 1 in created_at order (updated_at for shops, which
has no created_at). Remaps every foreign key, the user_shops composite
key, and productId strings inside orders.items jsonb. Foreign keys are
recreated with the ON DELETE actions the models declare, which also fixes
shops.chain_id and shops.owner_user_id missing SET NULL since 0011/0016.

Revision ID: 0027
Revises: 0026
Create Date: 2026-09-28

"""
from alembic import op

revision = "0027"
down_revision = "0026"
branch_labels = None
depends_on = None

# (table, column that orders new id assignment)
_TABLES = [
    ("chains", "created_at"),
    ("users", "created_at"),
    ("shops", "updated_at"),
    ("shop_photos", "created_at"),
    ("reports", "created_at"),
    ("shop_claims", "created_at"),
    ("products", "created_at"),
    ("orders", "created_at"),
    ("shipments", "created_at"),
]

# (child table, fk column, parent table, ON DELETE action, nullable)
_FKS = [
    ("shops", "chain_id", "chains", "SET NULL", True),
    ("shops", "owner_user_id", "users", "SET NULL", True),
    ("user_shops", "user_id", "users", "CASCADE", False),
    ("user_shops", "shop_id", "shops", "CASCADE", False),
    ("shop_photos", "shop_id", "shops", "CASCADE", False),
    ("shop_photos", "user_id", "users", None, True),
    ("reports", "shop_id", "shops", None, False),
    ("reports", "user_id", "users", None, True),
    ("shop_claims", "shop_id", "shops", None, False),
    ("shop_claims", "user_id", "users", None, False),
    ("products", "shop_id", "shops", "CASCADE", False),
    ("orders", "shop_id", "shops", "CASCADE", False),
    ("orders", "buyer_user_id", "users", "SET NULL", True),
    ("shipments", "order_id", "orders", "CASCADE", False),
]

# Indexes on remapped columns; dropped with the old columns, recreated verbatim.
_INDEXES = [
    "CREATE INDEX shops_chain_id_idx ON shops (chain_id)",
    "CREATE INDEX shop_photos_shop_idx ON shop_photos (shop_id, kind)",
    "CREATE INDEX shop_claims_user ON shop_claims (user_id)",
    "CREATE INDEX products_shop ON products (shop_id)",
    "CREATE INDEX orders_shop ON orders (shop_id, created_at DESC)",
    "CREATE INDEX orders_buyer ON orders (buyer_user_id)",
]


def upgrade() -> None:
    for table, order_col in _TABLES:
        op.execute(f"ALTER TABLE {table} ADD COLUMN new_id bigint")
        op.execute(
            f"""
            UPDATE {table} SET new_id = numbered.rn
            FROM (
                SELECT id, row_number() OVER (ORDER BY {order_col}, id) AS rn
                FROM {table}
            ) numbered
            WHERE {table}.id = numbered.id
            """
        )

    for child, col, parent, _action, _nullable in _FKS:
        op.execute(f"ALTER TABLE {child} ADD COLUMN new_{col} bigint")
        op.execute(
            f"UPDATE {child} SET new_{col} = p.new_id FROM {parent} p WHERE {child}.{col} = p.id"
        )

    # Line items snapshot productId as a string inside jsonb; remap while
    # products still has both ids. Unknown ids (deleted products) stay as-is.
    op.execute(
        """
        UPDATE orders SET items = (
            SELECT COALESCE(
                jsonb_agg(
                    CASE WHEN p.new_id IS NULL THEN li.item
                         ELSE jsonb_set(li.item, '{productId}', to_jsonb(p.new_id::text))
                    END
                    ORDER BY li.idx
                ),
                '[]'::jsonb
            )
            FROM jsonb_array_elements(orders.items) WITH ORDINALITY AS li(item, idx)
            LEFT JOIN products p ON p.id::text = li.item ->> 'productId'
        )
        """
    )

    # Children first so no FK constraint blocks dropping the parent ids.
    for child, col, _parent, _action, _nullable in _FKS:
        op.execute(f"ALTER TABLE {child} DROP COLUMN {col}")
    for table, _order_col in _TABLES:
        op.execute(f"ALTER TABLE {table} DROP COLUMN id")

    for table, _order_col in _TABLES:
        op.execute(f"ALTER TABLE {table} RENAME COLUMN new_id TO id")
        op.execute(f"ALTER TABLE {table} ALTER COLUMN id SET NOT NULL")
        op.execute(f"ALTER TABLE {table} ADD PRIMARY KEY (id)")
        op.execute(f"ALTER TABLE {table} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
        op.execute(
            f"""
            SELECT setval(
                pg_get_serial_sequence('{table}', 'id'),
                (SELECT COALESCE(max(id), 0) + 1 FROM {table}),
                false
            )
            """
        )

    for child, col, parent, action, nullable in _FKS:
        op.execute(f"ALTER TABLE {child} RENAME COLUMN new_{col} TO {col}")
        if not nullable:
            op.execute(f"ALTER TABLE {child} ALTER COLUMN {col} SET NOT NULL")
        on_delete = f" ON DELETE {action}" if action else ""
        op.execute(
            f"ALTER TABLE {child} ADD CONSTRAINT {child}_{col}_fkey"
            f" FOREIGN KEY ({col}) REFERENCES {parent}(id){on_delete}"
        )

    op.execute("ALTER TABLE user_shops ADD PRIMARY KEY (user_id, shop_id)")
    op.execute("ALTER TABLE shipments ADD CONSTRAINT shipments_order_id_key UNIQUE (order_id)")
    for stmt in _INDEXES:
        op.execute(stmt)


def downgrade() -> None:
    raise RuntimeError("0027 discards the uuid ids; downgrade by restoring a backup")
